lang: fr_FR
url: "https://jonathan-jeanniard.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jjeanniard" # the name of your site, e.g. ACME Corp.
tagline: "" #bref desc
description: "Ceci est mon portfolio qui représente une liste des projets, auquel j'ai participé ou réalisé dans tout type de langages." #desc

google_analytics: "UA-8529534-11"

author:
  twitter: jjeanniard

twitter:
  title: My Twitter
  username: jjeanniard

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata